- name: .local/bin
  file:
    owner: sky
    group: sky
    path: /home/sky/.local/bin
    state: directory

- name: desktop files
  copy:
    src: 'files/desktop/{{item}}'
    dest: /home/sky/.local/share/applications/
    owner: sky
    group: sky
    mode: 0755
  loop:
   - SOULCALIBUR VI.desktop
   
- name: copy wallpaper file
  copy:
    src: files/wallpaper.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root

- name: set wallpaper
  become_user: sky
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: set wallpaper position
  become_user: sky
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

- name: copy .bashrc file
  copy:
   src: files/bashrc
   dest: /home/sky/.bashrc
   owner: sky
   group: sky
   
- name: copy bash_aliases file
  copy:
   src: files/bash_aliases
   dest: /home/sky/.bash_aliases
   owner: sky
   group: sky

# udev


# services 
- name: copy system service files
  copy:
   src: 'files/services/{{item}}'
   dest: /etc/systemd/system/
   owner: root
   group: root
   mode: 0644
  loop:
   - wooting-xinput@.service 
  

- name: wooting udev rules 
  copy:
   src: 'files/udev/{{item}}'
   dest: /etc/udev/rules.d/
   owner: root
   group: root
   mode: 0644
  loop:
   - wooting-xinput.rules
   - wooting.rules
  register: udev

- name: activate looking glass tmpfiles
  shell: udevadm control --reload-rules && sudo udevadm trigger
  become: yes
  become_user: root
  when: udev.changed

# sudo udevadm control --reload-rules && sudo udevadm trigger

#- name: Start service httpd, if not started
#  ansible.builtin.service:
#    name: '{{item}}'
#    state: started
#    enabled: yes
#  loop:
#   - wooting-xinput@.service
#  when: service.changed
